version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    environment:
      MONGODB_URI: mongodb://mongodb:27017/viralizeai
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      REDIS_URL: redis://redis:6379

  mongodb:
    image: mongo:latest
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGODB_INITDB_DATABASE: viralizeai
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo_data:
